import fs from "node:fs/promises";
import path from "node:path";

const DOCS_URL = "https://api.tenero.io/api-docs/json";
const OUTPUT_PATH = path.join(process.cwd(), "src/lib/generated/teneroEnums.ts");

type OpenApiDoc = {
  paths?: Record<
    string,
    {
      get?: {
        parameters?: Array<{
          name?: string;
          schema?: {
            enum?: string[];
            anyOf?: Array<{ enum?: string[] }>;
          };
        }>;
      };
    }
  >;
};

function collectEnumValues(
  doc: OpenApiDoc,
  pathKey: string,
  paramName: string
): string[] {
  const params = doc.paths?.[pathKey]?.get?.parameters ?? [];
  const param = params.find((entry) => entry.name === paramName);
  if (!param?.schema) return [];

  const values: string[] = [];
  if (Array.isArray(param.schema.enum)) values.push(...param.schema.enum);
  if (Array.isArray(param.schema.anyOf)) {
    for (const item of param.schema.anyOf) {
      if (Array.isArray(item.enum)) values.push(...item.enum);
    }
  }
  return [...new Set(values)];
}

function unionFor(values: string[]): string {
  if (values.length === 0) return "string";
  return values.map((value) => JSON.stringify(value)).join(" | ");
}

async function main() {
  const res = await fetch(DOCS_URL, {
    headers: { accept: "application/json" },
    cache: "no-store",
  });
  if (!res.ok) {
    throw new Error(`Failed to fetch ${DOCS_URL}: ${res.status} ${res.statusText}`);
  }

  const doc = (await res.json()) as OpenApiDoc;
  const gainers = collectEnumValues(doc, "/v1/{chain}/market/top_gainers", "timeframe");
  const flows = collectEnumValues(doc, "/v1/{chain}/market/top_inflows", "timeframe");
  const marketStats = collectEnumValues(doc, "/v1/{chain}/market/stats", "timeframe");
  const hourlyNetflow = collectEnumValues(doc, "/v1/{chain}/market/hourly_netflow", "timeframe");
  const whaleMinUsd = collectEnumValues(doc, "/v1/{chain}/market/whale_trades", "min_amount_usd");
  const walletTradeStats = collectEnumValues(doc, "/v1/{chain}/wallets/{wallet_address}/trade_stats", "timeframe");

  const fileContent = `// Auto-generated by scripts/generate_tenero_types.ts
// Source: ${DOCS_URL}

export const TENERO_TOP_GAINERS_TIMEFRAMES = ${JSON.stringify(gainers)} as const;
export type TeneroTopGainersTimeframe = ${unionFor(gainers)};

export const TENERO_FLOW_TIMEFRAMES = ${JSON.stringify(flows)} as const;
export type TeneroFlowTimeframe = ${unionFor(flows)};

export const TENERO_MARKET_STATS_TIMEFRAMES = ${JSON.stringify(marketStats)} as const;
export type TeneroMarketStatsTimeframe = ${unionFor(marketStats)};

export const TENERO_HOURLY_NETFLOW_TIMEFRAMES = ${JSON.stringify(hourlyNetflow)} as const;
export type TeneroHourlyNetflowTimeframe = ${unionFor(hourlyNetflow)};

export const TENERO_WHALE_MIN_USD = ${JSON.stringify(whaleMinUsd)} as const;
export type TeneroWhaleMinUsd = ${unionFor(whaleMinUsd)};

export const TENERO_WALLET_TRADE_STATS_TIMEFRAMES = ${JSON.stringify(walletTradeStats)} as const;
export type TeneroWalletTradeStatsTimeframe = ${unionFor(walletTradeStats)};
`;

  await fs.mkdir(path.dirname(OUTPUT_PATH), { recursive: true });
  await fs.writeFile(OUTPUT_PATH, fileContent, "utf8");
  console.log(`Generated ${OUTPUT_PATH}`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
